### ISSUE TITLE
Cant run PixelPaint.exe on Linux

### ISSUE THREAD

**Issue by lbirkert** [CraftingDragon007/PixelPaint#3]
I tried running the provided PixelPaint.exe but it gave me an error!

**Comment by CraftingDragon007** [comment]
If you want to run PixelPaint on Linux you should use wine or a full windows vm. As for now I'wont make it native compatible on Linux

**Comment by KekOnTheWorld** [comment]
Thats crap man just use a cross platform alternative like qt or electron!
